### ISSUE TITLE
Do not skip if context is not production

### ISSUE THREAD

**Issue by ArnaudLigny** [reima-ecom/netlify-plugin-refresh-algolia#7]
Hello, thanks for your plugin, it's very useful ! 👍 

I have just one an observation/request: I think you should not skip if the context is not `production` because we can have use cases of test of the search engine on dedicated branches (for A/B testing).

Example:

```toml
[[context.abtest.plugins]]
  package = "netlify-plugin-refresh-algolia"
  [context.abtest.plugins.inputs]
    appId = "APP_ID"
    indexName = "preview"
```

I suppose it is possible to handle the plugin context with `netlifyConfig` and skip only if there is no config for the plugin in the current context?
